[package]
name = "red-simulation"
version = "0.1.0"
authors = ["Viacheslav Greshilov <slovaricheg@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "0.2.63", features = ["serde-serialize"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }
js-sys = "0.3.48"
hmac = "0.10.1"
sha2 = "0.9.3"
serde_json = "1.0.64"
serde = { version = "1.0.125", features = ["derive"] }

[dependencies.web-sys]
version = "0.3.48"
features = [
    "console",
    "CanvasRenderingContext2d",
    "Performance"
]

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
rand = "0.8.3"

[profile.release]
opt-level = "s"
panic = "abort"
