version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/red-demonstration'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'cargo'
    directory: '/red-simulation'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'cargo'
    directory: '/red-server'
    schedule:
      interval: 'weekly'
