version: "3.9"
   
services:
  db:
    image: postgres:13
    volumes:
      - reds-postgres-data:/var/lib/postgresql/data
    env_file: .env
    ports:
    - 5432:5432
volumes:
  reds-postgres-data:
