version: "3"

services:
  backend:
    image: greshilov/red-server:latest
    env_file: .env
    restart: always
    extra_hosts:
      host.docker.internal: host-gateway
    ports:
      - 8000:8000
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - reds-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  reds-postgres-data:
