version: "3.9"

services:
  backend:
    image: greshilov/red-server:latest
    env_file: .env
    restart: always
    extra_hosts:
      host.docker.internal: host-gateway
    ports:
      - 8000:8000
