version: "3.9"
   
services:
  db:
    image: postgres:13
    volumes:
      - reds-postgres-data:/var/lib/postgresql/data
    env_file: example.env
    command: ["postgres", "-c", "log_statement=all"]
    ports:
    - 5432:5432
volumes:
  reds-postgres-data:
