domains:
- domain: reds.greshilov.me
  type: PRIMARY
name: rust-event-driven-simulation
region: fra
static_sites:
- dockerfile_path: Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: greshilov/rust-event-driven-simulation
  name: rust-event-driven-simulation
  output_dir: /app/dist
  routes:
  - path: /
